#Server
server:
  port: 8088
#Logging
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
spring:
  #JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  #DataSource
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: kbl
    password: kbl
  #initData
  sql:
    init:
      mode: always